### ISSUE TITLE
Can't build/install on ubuntu18

### ISSUE THREAD

**Issue by bpinkney** [embeddedt/lv_img_conv#34]
I am getting the following when trying to install with npm after cloning the git repo:

```
/pinetime/lv_img_conv$ npm install
loadDep:yargs → 304       ▌ ╢██████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:tar → addNameRang ▌ ╢███████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine semver@7.5.4: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:set-blocking → re ▌ ╢███████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine are-we-there-yet@2.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:lru-cache → get   ▌ ╢███████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:mkdirp → request  ▄ ╢███████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:mkdirp → get      ▄ ╢███████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 5.4.0-149-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

All dependency steps are met otherwise.

Is there a way to avoid using npm for this step?

**Comment by embeddedt** [comment]
@bpinkney This is likely caused by 18.04 shipping a version of Node.js that's too old. I'd suggest using https://github.com/nvm-sh/nvm to install a newer version than what the distro packages provide. IIRC Node v14 and v16 both work, the error message you provided suggests you need at least v10.

**Comment by bpinkney** [comment]
@embeddedt : Thanks for the quick response.
I am able to run the command with node version 16 now.
However, even after successfully running "docker build -t lv_img_conv .", I am not able to see it on the path.
(e.g. "which lv_img_conv")

For context, I am trying to build InfiniTime, which relies on this library (but still get the following error).
```
CMake Error at src/resources/CMakeLists.txt:6 (find_program):
  Could not find LV_IMG_CONV using the following names: lv_img_conv
```

Do I need to manually add it to the path?

**Comment by embeddedt** [comment]
If you need it on the path, you should run `npm install -g lv_img_conv` from any folder, in order to install it globally. There might be a way to add cloned Node.js project repositories to the PATH but I am not aware of it.

**Comment by bpinkney** [comment]
OK, I guess that's even easier so long as I don't need to make any changes in lv_img_conv.

Thanks for your help!
